# -*- coding: utf-8 -*-
"""Task 1 Main Flow Services and Technologies.

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SuQ1ETgWH8qOjkRF8QW1hU-Z7Ck2HkfT
"""



"""Write a Python program to create a list, a
dictionary, and a set. Perform basic operations
like adding, removing, and modifying
elements.
"""

# Creating a list, dictionary, and set
my_list = [10, 20, 30, 40]
my_dict = {'a': 1, 'b': 2, 'c': 3}
my_set = {1, 2, 3, 4}

# Operations on the list
print("Original_List:", my_list)

# Adding an element to the list
my_list.append(50)
print("List after adding an element:", my_list)

# Removing an element from the list
my_list.remove(20)
print("List after removing an element:", my_list)

# Modifying an element in the list
my_list[1] = 25
print("List after modifying an element:", my_list)

# Operations on the dictionary
print("\nOriginal_Dictionary:", my_dict)

# Adding a new key-value pair to the dictionary
my_dict['d'] = 4
print("Dictionary after adding a new key-value pair:", my_dict)

# Removing a key-value pair from the dictionary
my_dict.pop('b')
print("Dictionary after removing a key-value pair:", my_dict)

# Modifying an existing key-value pair
my_dict['a'] = 10
print("Dictionary after modifying a key-value pair:", my_dict)

# Operations on the set
print("\nOriginal_Set:", my_set)

# Adding an element to the set
my_set.add(5)
print("Set after adding an element:", my_set)

# Removing an element from the set
my_set.discard(3)  # discard() does not raise an error if the element is not found
print("Set after removing an element:", my_set)

# Trying to modify a set element (not allowed, but we can remove and add)
my_set.remove(2)
my_set.add(20)
print("Set after simulating modification:", my_set)